config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :users
  post 'confirm'   => 'users#confirm'
  post 'check'   => 'todos#check'

end

app/models/restricted_action_count.rb
class RestrictedActionCount < ActiveRecord::Base
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
protect_from_forgery with: :null_session

  # POST /todos.json
  def create
    @todo = CreateTodo.run(todo_params)

    respond_to do |format|
      if @todo.valid?
        format.json { render json: @todo.result.to_json, status: :created }
      else
        format.json { render json: @todo.errors.messages, status: :unprocessable_entity }
      end
    end
  end

  # POST /check.json
  def check
    @todo = CheckTodo.run(user_id: params[:user_id], todo_id: params[:todo_id])

    respond_to do |format|
      if @todo.valid?
        format.json { render json: @todo.result.to_json, status: :ok }
      else
        format.json { render json: @todo.errors.messages, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:text, :checked, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery with: :null_session

  # POST /users
  # POST /users.json
  def create
    @user = Register.run(user_params)

    respond_to do |format|
      if @user.valid?
        format.json { render json: @user.result.to_json, status: :created }
      else
        format.json { render json: @user.errors.messages, status: :unprocessable_entity }
      end
    end
  end

# POST /confirm.json
  def confirm
    @user = Confirm.run({user_id: params[:user_id]})

    respond_to do |format|
      if @user.valid?
        format.json { render json: @user.result.to_json, status: :ok }
      else
        format.json { render json: @user.errors.messages, status: :unprocessable_entity }
      end
    end
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :confirmed_at)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devmeeting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :checked %><br>
    <%= f.check_box :checked %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Checked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.text %></td>
        <td><%= todo.checked %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @todo.text %>
</p>

<p>
  <strong>Checked:</strong>
  <%= @todo.checked %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :confirmed_at %><br>
    <%= f.datetime_select :confirmed_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Confirmed at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.confirmed_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Confirmed at:</strong>
  <%= @user.confirmed_at %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>